### ISSUE TITLE
feat: KeyPanelを実装する

### ISSUE THREAD

**Issue by dino3616** [shikosai33/shikosai33-web#44]
## 実装予定内容

- `Header` とカルーセル (名前忘れた) のリファクタも含みます

![image](https://github.com/user-attachments/assets/f0403b84-0cc2-4a24-9aec-2531dc0b3cb5)

## Figma の URL

https://www.figma.com/design/Ao44cG1Oi8XUiWBQM1vyk7/website?node-id=573-40020&t=PEcsujwPfBdf1bOv-4

**Comment by ReoHakase** [comment]
#75 で対応したのでcloseします
